par(mfrow=c(2,4), mar=c(3, 2, 2, 2))
barplot(table(if0), col=c("black", rep("gray",length(if0) )), border=NA,main=0)
barplot(table(if1), col=c("gray", "black", rep("gray", length(table(if1) -1)) ), border=NA,main=1 )
barplot(table(if2), col=c(rep("gray", which(names(table(if2)) == 1)), "black", rep("gray", length(table(if2) -1)) ) ,border=NA,main=2)
barplot(table(if4), col=c(rep("gray", which(names(table(if4)) == 3)), "black", rep("gray", length(table(if4) -1)) ), border=NA,main=4 )
barplot(table(if8), col=c(rep("gray", which(names(table(if8)) == 7)), "black", rep("gray", length(table(if8) -1)) ) ,border=NA,main=8)
barplot(table(if16), col=c(rep("gray", which(names(table(if16)) == 15)), "black", rep("gray", length(table(if16) -1)) ) ,border=NA,main=16)
barplot(table(if32), col=c(rep("gray", which(names(table(if32)) == 31)), "black", rep("gray", length(table(if32) -1)) ), border=NA,main=32)
barplot(table(if64), col=c(rep("gray",  which(names(table(if64)) == 63)), "black")  ,border=NA,main=64)
